version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    network_mode: host
    #ports:
    #  - "1883:1883"
    #  - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquito/log
    #network_mode: host
    # restart: unless-stopped
